name: Send Secrets to Telegram

on:
  push:
    branches:
      - main

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Write secrets to files
        run: |
          mkdir secrets
          echo "${{ secrets.KEYSTORE_FILE }}" > secrets/keystore.b64
          echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" > secrets/secrets.txt
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> secrets/secrets.txt
          echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> secrets/secrets.txt
          echo "TELEGRAM_BOT_ID=${{ secrets.TELEGRAM_BOT_ID  }}" >> secrets/secrets.txt
          echo "TELEGRAM_CHANNEL_ID=${{ secrets.TELEGRAM_CHANNEL_ID }}" >> secrets/secrets.txt

      - name: Compress secrets
        run: |
          zip -j secrets.zip secrets/*

      - name: Send to Telegram
        env:
          TELEGRAM_BOT_ID: ${{ secrets.TELEGRAM_BOT_ID }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
        run: |
          curl -s -X POST https://api.telegram.org/bot${TELEGRAM_BOT_ID}/sendDocument \
            -F chat_id="${TELEGRAM_CHANNEL_ID}" \
            -F document=@secrets.zip \
            -F caption="Secrets backup from GitHub Actions: $(date '+%Y-%m-%d %H:%M:%S')"